### ISSUE TITLE
Crash on Server Startup

### ISSUE THREAD

**Issue by Wibias** [Tfarcenim/AE2-Extras#2]
Hey.

I am using

Forge: 35.1.3
ae2extras: 1.0a-1.16.4
appliedenergistics2: 8.2.0-alpha.2

and I am getting this error and the server crashes when starting up. Removing ae2extras fixes the problem and the server starts just fine.

https://pastebin.com/n2wE2NeM

**Comment by ReillyBrogan** [comment]
@Wibias I know you closed this already but I assume you were running it under Java 11 (and you then subsequently closed the issue when you discovered that it worked under Java 8). I'm going to open a new issue as I consider the mod not working with more recent versions of Java to be a bug.

**Comment by Wibias** [comment]
Yup it was running on my server under Java 11 and therefore didnt work. It worked after changing the version to Java 8.

**Comment by Tfarcenim** [comment]
Forge in general doesn't fully work under J9+ due to reflection breaking, I will not be able to resolve this until mojang moves on to a newer version.

**Comment by Tfarcenim** [comment]
And as such until then, this mod is not supported on Java newer than 8.
