### ISSUE TITLE
Crash when ran with Java 11

### ISSUE THREAD

**Issue by ReillyBrogan** [Tfarcenim/AE2-Extras#3]
Forge 35.1.4
AE2 8.2.0-alpha.2
AE2 Extras 1.0a-1.16.4
Java 11.0.9 built by AdoptOpenJDK

Pastebin: https://pastebin.com/JJmiUic8

When the mod is removed the modpack can be launched successfully and a test world can be loaded. It'd be great if we could get this solved so that people can experiment with some of the new perf improvements in Java 11!

**Comment by Avakining** [comment]
I'm also getting it (almost the exact same crash), but different Java version:

Forge 35.1.4
ae2 extras 1.0a-1.16.4
ae2 8.1.0
Java 14.0.2.0

modpack is TNP Limitless 3, but I don't think that matters.

Please fix if you can. The new Curseforge app won't let me change back to Java 8 on mac :/
